added condition

diff --git a/.github/workflows/dev-docker-publish.yml b/.github/workflows/dev-docker-publish.yml
--- a/.github/workflows/dev-docker-publish.yml
+++ b/.github/workflows/dev-docker-publish.yml
@@ -33,6 +33,27 @@ jobs:
     - name: Run check_licenses script
       run: ./check_licenses.sh java
       shell: bash
+    
+    - name: Check exit status and set workflow status
+      run: |
+        if [ $? -eq 0 ]; then
+          echo "All certificates are valid"
+          echo "Success"
+        else
+          echo "Workflow failed due to faulty certificates"
+          echo "Failure"
+          exit 1
+        fi
+      id: set_status
+
+    - name: Set workflow status
+      run: |
+        if [[ "${{ steps.set_status.outputs.value }}" == "Success" ]]; then
+          echo "Success"
+        else
+          echo "Failure"
+        fi
+      id: final_status
 
     - name: Get version
       run:
